### ISSUE TITLE
Listings visible to partners and JAs outside of thier jurisdiction

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#1014]
Bug 
- In Doorway Partners, JAs (PII and non-PII) and Partners are seeing listings outside of their jurisdiction in the listings table. 

Expected Behavior
- Partners and JAs (PII and non-PII) should only see listings that correspond with jurisdictions they've been given access to. 

Notes: 
- https://exygy.slack.com/archives/C01Q4QG5R8Q/p1734458834917429

**Comment by emilyjablonski** [comment]
QA Notes
Create a partner and assign them only to some jurisdictions / listings. Ensure they only see those listings in the list.
