### ISSUE TITLE
[UI][Starter] Build custom zoom in/out buttons for the map

### ISSUE THREAD

**Issue by lisunshiny** [metrotranscom/doorway#121]
Our mocks have a custom zoom in/out UI component, lets update with that

#### Before
<img width="508" alt="Screenshot 2023-05-15 at 6 19 19 PM" src="https://github.com/metrotranscom/doorway/assets/10789523/aae58c6d-dc5d-4dad-b50a-98979644cfe5">

#### After (screenshot of mock, see Figma for actual specs -- no need to build transit just zoom buttons)
<img width="570" alt="Screenshot 2023-05-15 at 6 19 48 PM" src="https://github.com/metrotranscom/doorway/assets/10789523/8ce74a94-3f37-40bf-afc7-4b0d46e2ec7c">

One possible way to do this:
* Make a new react component  for the zoom in/out functionality
* Make it zoom in and out on click
* Somehow hide the native Google Maps zoom buttons
* Add the component you made to BOTH the listings and listing maps and position correctly

Also this SO answer is pretty useful: https://stackoverflow.com/questions/7916555/custom-google-map-api-v3-zoom-buttons

**Comment by isaac-looker** [comment]
The listing maps, actually don't zoom- they are an <a /> that open an actual map.
