### ISSUE TITLE
update seed scripts for doorway

### ISSUE THREAD

**Issue by lisunshiny** [metrotranscom/doorway#13]
- change jurisdiction env var to "doorway"
- add new  doorway jurisdiction, remove non-doorway ones
- add new listings under doorway jurisdiction (make sure to include `county`)
- add instructions on how to reseed

**Comment by phattya** [comment]
https://github.com/metrotranscom/doorway/pull/15

**Comment by phattya** [comment]
@lisunshiny should this be closed?
