### ISSUE TITLE
Maps links not always working

### ISSUE THREAD

**Issue by phattya** [metrotranscom/doorway#163]
**Describe the bug**
Maybe something to do with the Suite # in the address?  So far I see this happening on the ones with the SF (now San Ramon) address: 548 Market Place Suite #59930, San Ramon, CA 94583

**To Reproduce**
If you go to a listing like `[doorway] Test: Default, Missing Household Levels in AMI` and click on `View on Map` or the map at the bottom of the page, it doesn't take you to the address associated with the listing, but rather adds the address in the gMaps search & shows you a map near you (mine showed me the beaches)
![image](https://github.com/metrotranscom/doorway/assets/12400715/f95684d9-566c-4b05-baad-e8282334e6bf)

![image](https://github.com/metrotranscom/doorway/assets/12400715/2b50eb8f-9a55-482e-955a-e4d824b12e86)

**Expected behavior**
Go to the Listing location on the map.

**Comment by ifranch** [comment]
This is the existing behavior from "view on map" in Bloom, which is to search the address name in gMaps, and not use the coordinates. This might just be an issue with the testing data since it might not be a real address, so do we want to still change the behavior?

**Comment by phattya** [comment]
@ifranch great points! From my testing, it seems to happen when there's a suite #, so it doesn't pull the entire address (ie there's no state or city shown), which would give it a better chance of accuracy. 

![image](https://github.com/metrotranscom/doorway/assets/12400715/6d29fedf-2523-4b5c-ac99-d36356f13d15)

![image](https://github.com/metrotranscom/doorway/assets/12400715/ca7eb170-d148-4270-9b18-a57012ec4f28)

It's interesting that it doesn't just use lat/lon, since every building address has to have that, however we don't need to improve it's current functionality.  I think we'd just want to ensure the entire address makes it to gMaps. We can leave it and see if we want to prioritize it as part of the bug bash next week, if you want.

**Comment by sarahlazarich** [comment]
should prioritize

**Comment by sarahlazarich** [comment]
fixed
