### ISSUE TITLE
Partners site Inactivity Warnings & Logout Errors on Public site

### ISSUE THREAD

**Issue by phattya** [metrotranscom/doorway#192]
**Describe the bug**
When logged in on the Partner's site, the Public site also recognizes the user logged in. Due to this, it will alert about inactivity when applicable and reroute to the login screen typically used by housing seekers, but since we've disabled that for . Do we want to block this from happening? Or think that it's a small enough use case (someone logged in to Partners portal and checking Public listing info and timing out), that we are fine with the behavior?  This will also stop happening once applications are accepted on Doorway.

**To Reproduce**
Log into Partners Portal and have the public site open on another tab/window. Wait for the login to time out and require a new log in, and the Public site will switch to this error bc it forwards to the login screen.
![image](https://github.com/metrotranscom/doorway/assets/12400715/7b2e03b6-af67-4768-8aa6-4af4bdf4aa5c)

**Expected behavior**
No error message or inactivity notifications on the Public site.

**Comment by sarahlazarich** [comment]
good to close
