### ISSUE TITLE
Code review is not enforced to merge into main

### ISSUE THREAD

**Issue by lisunshiny** [metrotranscom/Doorway#2]
![image](https://user-images.githubusercontent.com/10789523/215882751-eec3a0a9-93db-4ef2-8238-f182fc9bc654.png)

(I'm also assuming that the main branch is not protected if this is true)

**Comment by phattya** [comment]
@lisunshiny thanks for the callout. I haven't spent any time double checking the settings. I just now added a branch rule for reviews, but we should probably check all the settings. Let's discuss.
