### ISSUE TITLE
Get Cypress test working on github actions

### ISSUE THREAD

**Issue by ludtkemorgan** [metrotranscom/doorway#244]
For current PRs we have the following checks that are run in github actions:
- Backend unit tests
- Backend e2e tests
- Unit tests shared helpers
- unit tests partners
- Unit tests Public
- Unit tests listing imports
- Linting

There are cypress tests built for both the partner and public sites but they are not being run anywhere for PRs (or anywhere in the pipeline)

Cypress is more complicated to run in github actions than the unit tests, but it is theoretically possible. Cypress has a plugin to get it to work https://github.com/cypress-io/github-action which we should be able to utilize.

**Comment by emilyjablonski** [comment]
QA Notes
There is no QA needed from product here, it can be closed once in QA
