### ISSUE TITLE
Landing page - Help Center isn't highlighted in blue when selected

### ISSUE THREAD

**Issue by ludtkemorgan** [metrotranscom/doorway#247]
When a page associated to the help center is selected, the "help center' label is not highlighted blue like it does for welcome and "view listings"

1. Click on a page from the "help center" drop down
2. The words "help center" is black instead of blue 

![image](https://github.com/metrotranscom/doorway/assets/42942267/b77954b0-530c-48ce-9a3e-fd3cc5c789b6)
vs
![image](https://github.com/metrotranscom/doorway/assets/42942267/78e27f78-f129-47fc-a7f9-a07752e36e84)

**Comment by sarahlazarich** [comment]
this is complete
