### ISSUE TITLE
When going to second page of multiple listings view, the user is taken to the bottom of the list on the second page

### ISSUE THREAD

**Issue by ludtkemorgan** [metrotranscom/doorway#248]
When going to second page of multiple listings view, the user is taken to the bottom of the list on the second page

**To Reproduce**
1. Go to the listings page
2. Scroll to the last listing and click page 2 on the pagination
3. The second page of listings is shown but it is at the bottom of the list

**Comment by sarahlazarich** [comment]
duplicate ticket, closing

https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/297
