### ISSUE TITLE
Text is not centered on check-boxes

### ISSUE THREAD

**Issue by ludtkemorgan** [metrotranscom/doorway#254]
**Describe the bug**
The county selection checkboxes does not have the text centered to the middle of the checkbox

![Screenshot 2023-07-11 at 11 21 31 AM](https://github.com/metrotranscom/doorway/assets/42942267/af9e81fa-ca05-457c-9260-0f1a8754ba6b)

**To Reproduce**
1. Go to the homepage
2. Scroll down to the county selection section and notice the misalignment

**Comment by sarahlazarich** [comment]
emily did this! closing
