### ISSUE TITLE
Navbar - create a "Property Managers" tab

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#257]
As a Property manager that comes across the public site, 
I want to see a "Professional Partners" section in the navbar
So that I can view information about Doorway that is relevant to my role. 

**Description:** 
In the navbar, the professional partners link would open a new page with an overview of the benefits for professional partners. This should include a sign in link to Partners. 

Content is [here](https://docs.google.com/document/d/12FEQPqAgH3t96IviNgPxox-Bj3j0IqkCdfWYa7h_MYs/edit) 

Note is that we want to remove the accordion links from the content, so that this page is just structured as headings and content. We did this to avoid any accessibility issues.  

<img width="835" alt="Screenshot 2023-07-20 at 5 07 32 PM" src="https://github.com/metrotranscom/doorway/assets/118844176/8fc442f5-b150-4637-841d-b6c2a5cf358c">

Note: 
- We are not going to do translations for the first pass, except for the Navbar heading, which we can translate in localize.

**Comment by sarahlazarich** [comment]
@KrissDrawing this is ready to pull in!

**Comment by KrissDrawing** [comment]
@sarahlazarich how should i handle content from doc that is below "Appendix" ?

**Comment by sarahlazarich** [comment]
@emilyjablonski -- BAHFA would actually like the section in the navbar should be called "Partners" instead of "Professional Partners". Can we make this change please?? Translations are below! 

Partners: 
- Chinese - 夥伴
- Spanish - Socios
- Filipino - Mga kasosyo
- Vitmamese - Đối tác

**Comment by emilyjablonski** [comment]
QA Notes for SiteHeader

This PR makes some changes and fixes in the SiteHeader component that arose out of issues in Doorway after adding more links to the SiteHeader. Design has signed off on this behavior.

Example of some of the bugs in Doorway right now
![268129587-45665530-3543-4c2f-9b54-cbdfe78b2f34](https://github.com/bloom-housing/ui-components/assets/65367387/23fdcd07-8ea3-489b-9c4c-a1f6c8ac4059)


Changes / fixes in this PR:
*  The SiteHeader component now wraps the links container onto the next line if any individual link becomes long enough to wrap onto two lines when the container is centered with the logo. It is dynamic based on the size left in the container. The current SiteHeader is buggy in that long links will overlap behind the logo at tablet screen sizes and become hidden. You can see this in [this new story](https://deploy-preview-124--storybook-bloom-dev.netlify.app/iframe.html?args=&id=headers-site-header--long-links&viewMode=story) as you transition from desktop to mobile. The loose mock for this is [here](https://www.figma.com/file/LKuDbvssNcaKHFJjrSIf3j/doorway-library?type=design&node-id=211-2736&mode=design&t=IzZsG6mKAaZP9gNe-0), but it is not meant to be 1-1, just a sense of the layout. The links when wrapped are meant to be left aligned. Accomplishing having different styling on the links only when the flex box wraps was sort of funky. There isn't any sort of event. We are already listening to the browser resize event for other UI behavior, so as the browser resizes we're checking to see if the links have wrapped and then applying the needed styles. This wrapping is easily turned off if needed through CSS overrides.
* Dropdown items in the header now will wrap onto multiple lines if needed. Previously they never wrapped and could result in the other multi-word nav items being extra squished. There was additional accommodation needed here to make sure that dropdown items can wrap but that the dropdown icon is never wrapped onto its own line.
* The Doorway PR was the first instance of another new state which was having two dropdowns next to each other. The SiteHeader currently doesn't work with two dropdowns / doesn't close them appropriately, so there are some changes here to how we are storing the active menu to fix that. You can ensure that works in the same [new story](https://deploy-preview-124--storybook-bloom-dev.netlify.app/iframe.html?args=&id=headers-site-header--long-links&viewMode=story) just by hovering between each dropdown.
* Our dropdown menus were positioned sort of strangely which was exacerbated now that we have two next to each other, so there are changes here to how we are positioning the dropdowns. Now they always show up exactly underneath their parent, right aligned, and are at least as wide as the parent, but will extend to the left to allow for more space for the dropdown items without wrapping the text.

**Comment by ludtkemorgan** [comment]
@sarahlazarich This can be viewed in the dev environment: https://dev.housingbayarea.mtc.ca.gov/

**Comment by sarahlazarich** [comment]
looks great! @ludtkemorgan, lmk when this is in staging and we can give BAHFA a sneak peek.
