### ISSUE TITLE
Security - SCA and DCA scanning setup for application

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#261]
Per the recommendations in the [security overview](https://docs.google.com/document/d/14WXLSrsQEhenchPwGSmX1yt1ZaV_k9Bb8lbJsYiTpFA/edit), set up SCA/DCA scanning

**Comment by ludtkemorgan** [comment]
Snyk has been setup in the Doorway repo. I will continue to refine the configuration and make sure it is setup for all of the use cases we need
