### ISSUE TITLE
Partners Terms of Service UX / Link Issue

### ISSUE THREAD

**Issue by emilyjablonski** [metrotranscom/doorway#278]
![Screenshot 2023-07-27 at 11 38 54 AM](https://github.com/metrotranscom/doorway/assets/65367387/e0472f81-3e86-463f-8ec1-2666608f3c2f)

Putting a link to the TOS vs the TOS itself seems like an unintended pattern of this component. It also doesn't open in a new tab, so you have to back track to accept the terms.

**Comment by sarahlazarich** [comment]
no0 longer present
