### ISSUE TITLE
Add health check endpoint for backend

### ISSUE THREAD

**Issue by chriscasto** [metrotranscom/doorway#28]
The ALB fronting the backend API needs a health check endpoint that it can ping to make sure the backend is operational and healthy.  Currently it's using the `/jurisdictions` endpoint, but this is probably heavier than needed and may put unnecessary load on the DB and/or backend

**Comment by sarahlazarich** [comment]
pull in sooner rather than later

**Comment by sarahlazarich** [comment]
dupe of https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/256
