### ISSUE TITLE
List components that were changed

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#292]
https://www.notion.so/exygy/Doorway-Engineering-Component-Audit-b657c6ca0ab74559afbc292d3a9b4898

In Notion, create an audit of Doorway implementation of UIC. This audit should contain the following:

List components that were edited by DW and what changed

**Comment by sarahlazarich** [comment]
3 day timebox!!!!!!!

**Comment by emilyjablonski** [comment]
No QA needed from product/design
