### ISSUE TITLE
Number of Bedrooms not ordered on listings page

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#295]
On the listings detail page, the units are not ordered by bedroom number. Please also investigate this in HBA/Core to see if this also exists there. 
Ex.
![image.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/ad0b76c0-e68a-47b3-9736-57099afc8049)

AC:

The units should be ordered by number of bedrooms.

**Comment by KrissDrawing** [comment]
QA Notes: Issue was only present for 4 and 5 br as they were not added to sort array. I changed that in core, so for now it should work fine in https://bloom.exygy.dev/.

**Comment by sarahlazarich** [comment]
LGTM, thank you Kris
