### ISSUE TITLE
Listings page pagination

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#297]
When going to second page of the listings page, the user is taken to the bottom of the list on the second page. They should be taken back to the top of the list on a new page.

AC:

When there are multiple pages of listings, and a user clicks over to the next page, they should be taken to the top of the new page.
![image.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/bf7870da-f768-4200-a8f8-a99f583a9cf7)
![image.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/ba184975-a945-4068-868d-a2425abd115c)

**Comment by KrissDrawing** [comment]
QA Notes: on page change listing container will scroll top, also whole page will scroll to top.
Should be also applied for mobile view, and mobile view when expanded
