### ISSUE TITLE
UX for property managers to request approval

### ISSUE THREAD

**Issue by emilyjablonski** [metrotranscom/doorway#307]
The following changes will only affect the partner's portal experience of a partner and not a super administrator.
- On a new or draft listing, a partner should see the request approval button reflected in the Figma below
- If clicked, it should open a modal confirming that they would like to request approval
- On submit, the status on the listing should change to a pending status (reflected in the pill) and throw a toast
- When in the pending status, the edit button should not be available in this state
- Signing in as an administrator, the only visible change is the status update to pending
Notes: These changes should not include any backend work beyond updating the status of the listing on modal submit. Further functionality will be implemented in later tickets.

[Figma](https://www.figma.com/file/cNRVrLdz8cjXQdSr54BRao/Approval?type=design&node-id=1607-68638&mode=design)

**Comment by emilyjablonski** [comment]
QA Notes
When listings approval is on:
* When a partner submits a listing for approval, they get a modal asking them to confirm. When submitted, the status of the listing changes to pending approval.

When the feature is both on or off:
* Now using the ui-seeds Tag component in order to be able to match the pill designs for listings approval (the CSS overrides worked great!) - I updated to the new seeds Tag everywhere we were consuming UIC Tag in partners so that it stays visually consistent (locations below).
-- Listing form pages (Tag is the listing status
-- Application table pages (Tag is also the listing status)
-- Individual application form (Tag is the submission status of the application)
-- Application flagged set resolution page (Tag is the resolution status of the set)
-- User edit form (Tag is the confirmed status of the user) - (previously this was a Tag size that was inaccessible / we no longer support it, so now it's a little bigger)

Check out the new pill visually in the places it was updated.
Ensure if you have the environment variable on that as a partner/jurisdictional admin when you create a draft listing and submit it for approval that a modal pops that matches the designs. On submit the status should change to pending approval.

**Comment by sarahlazarich** [comment]
@emilyjablonski -- I didn't see the modal or UX from the designs, wondering if I need a different link?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWRHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2a4e77c341bac9c54360ee7a8d638f813e2e9094/image.png)

**Comment by emilyjablonski** [comment]
@sarahlazarich it's in the Figma linked above, I tagged you on the modal

**Comment by sarahlazarich** [comment]
I see the designs from the modal in Figma! But when I go https://bloom-partners-listings-approval.netlify.app/, I can create + publish a listing directly, and the new UX doesn't seem to be reflected

**Comment by emilyjablonski** [comment]
@sarahlazarich Just want to confirm that you're testing as a partner?

**Comment by sarahlazarich** [comment]
Update: Em and I are having issues logging in / QAing in this env, emily is troubleshooting
