### ISSUE TITLE
Add 120% AMI Levels

### ISSUE THREAD

**Issue by iph-97** [metrotranscom/doorway#311]
We have a request to add 120% AMI units to the Doorway Housing Portal. They can be found in this [spreadsheet](https://docs.google.com/spreadsheets/d/1FIYA_u0P0PkxWN1Ztg-ipzEjmjGTAVRo4Yjr9tastOo/edit?usp=sharing) and are highlighted in yellow (so not new charts, just new additions to existing charts). The update for Contra Costa County is a time sensitive request for a listing, so is medium high priority. All others are low priority. 

QA must be done in staging: https://partners.staging.housingbayarea.mtc.ca.gov/
1. Sign in
2. Go to a listing
3. Add a unit and explore the AMI options to verify that the information highlighted in the sheet above in accurately reflected in staging.

**Comment by ludtkemorgan** [comment]
These are in staging environment: https://partners.staging.housingbayarea.mtc.ca.gov/

**Comment by sarahlazarich** [comment]
lgtnm
