### ISSUE TITLE
Jurisdictional Refactor

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#319]
Go through the jurisdictional refactor outlined in this [TDD](https://docs.google.com/document/d/1qiWyN2Fxj_wMJsgGbQQSjbvrdPBsdO3h7agL-LR6mIU/edit#heading=h.bknox3ib8wpb )

QA:
1. Ensure existing listings have jurisdictions that match the county of their address
2. Try adding a new unit and ensure that the ami-charts available match the jurisdiction that the listing is assigned to.
3. On the public side, ensure that the notificationsSignUpUrl is functional on the listings page, and the listing detail page shows utilities included in the additional fees section (if enabled). For reference Test:Coliseum is seeded to have it enabled.

**Comment by ludtkemorgan** [comment]
@sarahlazarich when we release this to production the following changes will be noticeable by the users:
- New listing will not be required to select a jurisdiction when creating the listing (the list should be the same as county plus a "Bay area" one)
- When adding a new user "jurisdictional admin" will now be an option
- Preferences will need to be assigned to the correct jurisdiction (this is something we will do for them on existing preferences in the system)
- AMI chart dropdown will only show the AMI charts associated to the jurisdiction selected for the listing
