### ISSUE TITLE
Update Partners UI from County to Jurisdiction Question

### ISSUE THREAD

**Issue by ColinBuyck** [metrotranscom/doorway#340]
The current experience is shown below:
<img width="940" alt="Screenshot 2023-09-06 at 10 43 39 AM" src="https://github.com/metrotranscom/doorway/assets/53269332/fb6fc34f-d7ca-4526-937d-a23bde3a4086">

Re-enable jurisdiction dropdown and touch base with design and product on if disclaimer box on the right should still be included and if so, where.

Note: This should be released prior to the migration mapping listings from county to newly added jurisdictions.

**Comment by ludtkemorgan** [comment]
@eajensenwa Can you look into if we should move this box to the jurisdiction dropdown

**Comment by eajensenwa** [comment]
@ColinBuyck lets leave the box where it is for now, since I sounds like there is some confusion for users around having to move to different portals to generate listings for other counties. Once all HBA counties are migrated to doorway, we can probably remove that box!

**Comment by ludtkemorgan** [comment]
@ColinBuyck Sounds good. Thanks for looking into it. Go ahead and close this ticket

**Comment by ColinBuyck** [comment]
No changes needed
