### ISSUE TITLE
Create automated email Handlebar template

### ISSUE THREAD

**Issue by ludtkemorgan** [metrotranscom/doorway#348]
As part of the [automatic email notification feature](https://github.com/bloom-housing/Bloom-Doorway/issues/25) we will need to create a handlebar template that we can then send. 

Design Template: https://www.figma.com/file/0Rj4I74uO1UTBkHzDR25UD/Automated-Email-Templates?type=design&node-id=1607-68638&mode=design&t=wv7FKcX2qxWmCIpM-0

Outcome of this ticket it to create a handlebar template(s) to look like the above template. 

Note: we can avoid putting in the unsubscribe link for now as that might need to be done on the admin side and will differ depending on what tool we use (sendgrid or govdelivery)

**Comment by emilyjablonski** [comment]
QA Notes:
There is nothing for product to QA since this was just the template and it isn't trigger-able in the app.
