### ISSUE TITLE
Automated Listing Email - Add unsubscribe button to email

### ISSUE THREAD

**Issue by ludtkemorgan** [metrotranscom/doorway#370]
Any marketing email needs to have an unsubscribe option. This applies to the automated emails for a new listing since we are sending it to a subscriber list.

In order to do this we will need to do some investigation on if GovDelivery automatically adds that to bulletin emails or if we need to  manually add those ourselves.

If we do need to add it ourselves reference the [figma design](https://www.figma.com/file/0Rj4I74uO1UTBkHzDR25UD/Automated-Email-Templates?type=design&node-id=1607-68638&mode=design&t=wv7FKcX2qxWmCIpM-0) for the look and feel of the link. Work with Morgan to get the proper unsubscribe link

**Comment by sarahlazarich** [comment]
Whoever picks this up needs to research how GD handles this, but we need to figure out if GD provides an unsubscribe button or if we need to link to it. Morgan can provide documentation. ML recommends assuming that we'll need to link ourselves for the sake of pointing here. 

Are we expecting any feedback or experience after the button is clicked?
- depends on GD unsubscribe experience 
- If there's no "you are unsubscribed page!", might need to get with design 

Testing?
- We can test in staging 
- Only ML has admin creds in staging, API creds will be in dw-config repo

**Comment by ludtkemorgan** [comment]
It looks like the unsubscribe button comes by default:
<img width="549" alt="image" src="https://github.com/metrotranscom/doorway/assets/42942267/5f265cda-32d8-46de-ac9b-42e84b7a2684">

In staging at least it brings you to the "subscribe" form so more investigation will be needed to see if this is expected
