### ISSUE TITLE
Update email in doorway footer

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#374]
Description: The email in the footer of the doorway public site is currently bahfa@bayareametro.gov - this needs to be changed to doorway@bayareametro.gov

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4db272fde9bc16ec9f17999fac66679ac18a7c6b/image.png)

AC: 
The footer email is updated to doorway@bayareametro.gov.

**Comment by ludtkemorgan** [comment]
@sarahlazarich this is in [Doorway dev](https://dev.housingbayarea.mtc.ca.gov/) and will be in staging shortly
