### ISSUE TITLE
Adjust live alone to radio

### ISSUE THREAD

**Issue by emilyjablonski** [metrotranscom/doorway#383]

**Comment by emilyjablonski** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91e5e22e649054121d9994c8fedfa6d59691f860/Screenshot%202023-11-01%20at%204.09.04%E2%80%AFPM.png)

**Comment by jaredcwhite** [comment]
This is now in Core, but we can QA it here once those changes have come over to Doorway.
