### ISSUE TITLE
Common App Question Review

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#399]
Review the [common app questions] (https://docs.google.com/document/d/1Bgf2BTHohJRUrJ-JFvrjgrEbDW40usuh7zKzwze2h2U/edit#heading=h.z2we68wtdnff) and confirm that the question types are supported and identify any technical barriers to putting them in doorway.

**Comment by ludtkemorgan** [comment]
I think there will only need to be one backend change for these questions as they currently stand. I have added a comment to the doc, but it is that we would need to add a new field to the applications table to handle the separation of vouchers into two questions. That should be an easy change. We would just need to decide on how we handle that in core or if that is just a change we make in Doorway

**Comment by ludtkemorgan** [comment]
@sarahlazarich I moved this ticket to QA, let me know if you are looking for any other information
