### ISSUE TITLE
Split voucher and Section 8 question 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#410]
On the application in Doorway, we want to split the "Do you currently receive section 8 voucher or rental assistance" question in to two.  This will require a new field for the applications table in the backend since section 8 and vouchers are just one field.

https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/399

Designs: https://www.figma.com/file/7EYcF5hl05GVVeqtkWGmvF/Dwy-Questions?type=design&node-id=2523-4946&mode=design&t=bou6FCndIy4roioA-0

Things to do:
- new backend field
- Application now has two questions with new language
- Application summary
- Paper application
- CSV export

Question: 
- should we do this in core as well? 
  - For now do it in doorway and we can pull it back to core in the future if need be

**Comment by sarahlazarich** [comment]
Question currently saved as a boolean value 
Will need to make a new one for new question 
Will need to backfill in Core 

Can do the BE only in Core, or do both depending on the jurisdictions 
Would need to consider the number of small FE changes that we'd come across, and csv exports, also be mindful of Detroit experience, paper app, translations 

- Will need designs, Sarah to submit a notion ticket with a due date to design

**Comment by sarahlazarich** [comment]
@slowbot can you link designs here if you have them?

**Comment by jaredcwhite** [comment]
I have a few questions:

* Is there a term of art for the rental assistance portion of the split? Is calling it "rental assistance" correct, or is there some other term we should use for naming fields/page titles/URLs/etc.?
* When will we have sign-off on the proposed title and description for each page?
* I'm assuming we'll need to get new translations then?

**Comment by jaredcwhite** [comment]
Another question: for the CSV Export, is there any particular naming needed for the two columns? Is "Vouchers" & "Rental Assistance" OK?

**Comment by sarahlazarich** [comment]
@jaredcwhite  -- 

- Rental assistance is the correct term! 
- We are waiting on that from Doorway now - hopefully very soon! 
- We will need updated translations -- but we're still in the process of figuring that out with Doorway. 
- Those titles sound great!

**Comment by jaredcwhite** [comment]
Based on recent comments on #457, we won't be moving forward on this feature.
