### ISSUE TITLE
[Spike] AWS email configuration for user emails 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#413]
Outline steps for what it will take to switch user emails from Exygy's sendgrid to AWS, including cost.  Can reference Chris Casto's cost comparison document as well.  

1 day / ~8hr timebox

**Comment by ludtkemorgan** [comment]
Initial notes:
- We should use [Amazon SES](https://us-west-2.console.aws.amazon.com/ses/home) to send emails.
- We currently have SES setup, but it is in us-west-2. I believe we will need to have it setup in us-west-1 using [these steps](https://aws.amazon.com/getting-started/hands-on/send-an-email/)
  - Morgan already set this up for us-west-2 and can assist with the this
  - We need to decide on the email that it will be sent from which might take additional work if it's an email that currently doesn't exist
- Connecting in the code can be done via the [javascript aws-sdk](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/ses-examples-sending-email.html)

**Comment by sarahlazarich** [comment]
can we use the existing hba email (the one we use for listing approval?) or do we need to set up a new one?

**Comment by emilyjablonski** [comment]
See https://github.com/metrotranscom/doorway/issues/323 for notes!
