### ISSUE TITLE
Spike - Listing Notification Translations 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#421]
As a user on Doorway signing up for email notifications, 
I want to be able to view the email in spanish, chinese, vietnamese, or tagalog 
So that I can consume the content in my preferred language

AC: 
- Users on doorway have a way to receive translated emails 

Notes:
- I understand that we may not be able to translate emails for folks who have already signed up for notifications. That’s ok for now. 
- I think there are a few different ways this could be done - as a first step on this ticket, can we outline those (the experience for a user, including a sense of complexity) so we can run past Barry?) 

outcome of the spike is to document the options and present the best option.

**Comment by ludtkemorgan** [comment]
Timebox to 1 day
