### ISSUE TITLE
Account theming for Doorway 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#422]
As an applicant signing up for an account on Doorway,
I want to have my account experience be consistent with the rest of the doorway site

AC: 
- Doorway accounts experience is consistent with the rest of the site. 

Notes: 
For discussion with Design and Eng on 11/22:  
- Will Eng need theming instructions from design on this? It seems possible that most the use cases will have been covered in previous design documentation, so they might not be necessary at this point. Screenshots of the pages that would need to change are below. 
- Designs: https://www.notion.so/exygy/Account-Theming-5633e0a281ef449381bbd5a0ab9d8d58#171988339e2d48a0883b8047cbcfee79 
- https://www.figma.com/file/ihaZA5QibRRJFyBdARKn55/User-Accounts?type=design&node-id=2658-28648&mode=design

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy80QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ade10411d69f5cdd7feabdc2df105d2a111b75d6/Screenshot%202023-11-21%20at%204.02.23%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2I1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ee43c80c4db0c540736c94ccdd712e476509c56/Screenshot%202023-11-21%20at%204.05.28%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1Q1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--feefbe354c30e66db5f096093807402015052cdf/Screenshot%202023-11-21%20at%204.03.02%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2Y1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--70cf1fe9df274607f7ee0e48cf517ddc642b1601/Screenshot%202023-11-21%20at%204.05.37%E2%80%AFPM.png)

**Updated AC**
After recieving the feedback below and the update that tweaks to the application submission confirmation page should be included in this ticket, PR #3853 was created
<img width="864" alt="Screenshot 2024-02-01 at 4 00 49 PM" src="https://github.com/metrotranscom/doorway/assets/53269332/c88de73e-1e60-49bc-ab03-df363f41b030">
<img width="397" alt="Screenshot 2024-02-01 at 4 08 33 PM" src="https://github.com/bloom-housing/bloom/assets/53269332/42c9cbdf-7825-4ca1-96c6-95eda7120ee0">

Core QA: https://bloom.exygy.dev/
1) Sign in on the public side
2) Apply to a few different listings
3) Explore the account dashboard, account applications view, and account settings with the Figma (see PR description notes first!)

**Comment by ludtkemorgan** [comment]
Designs are needed on this

**Comment by sarahlazarich** [comment]
@ludtkemorgan -- designs are linked now.

**Comment by sarahlazarich** [comment]
Dev notes: 
- no need to add side nav, if spacing is the same in core and only colors change 
- create a new ticket for the side bar

**Comment by sarahlazarich** [comment]
@slowbot to pull in mobile designs
