### ISSUE TITLE
Dwy: Paper Applications not Downloading

### ISSUE THREAD

**Issue by iph-97** [metrotranscom/doorway#432]
Babs and Vu-Bang noticed that paper application downloads on Doorway were not working for San Antonio Place, they tried uploading a new PDF and the issue persisted. I was able to confirm that other listings with paper apps also are not downloading. When you click the 'download application' button, nothing happens. This is a high priority item.

**Comment by sarahlazarich** [comment]
resolved https://exygy.slack.com/archives/C02G1S19QA2/p1701463406392389
