### ISSUE TITLE
Listing Filter Showing Incorrect Results

### ISSUE THREAD

**Issue by iph-97** [metrotranscom/doorway#459]
Babs noticed that when filtering the available properties on Doorway, the unit filter was not working properly. When filtering for only studios, results for 1 BRs also appeared. This is a medium priority issue :large_yellow_circle:.

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem5WQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--375915f5a8d019e8fd17ca31e00f8ff8709714d6/image.png" alt="image.png" />

**Comment by sarahlazarich** [comment]
closing, since this is not a bug per https://exygy.slack.com/archives/C02G1S19QA2/p1705512830872919. Can make a follow up if we need to update.
