### ISSUE TITLE
Remove ability to download or view application data after 45 days 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#492]
As a Partner or Jurisdictional Admin user in Doorway, 
I do not want to see any applicant information 45 days after the listing closes,
So that I do not have any PII access that I don't need. 

[Design](https://www.notion.so/exygy/671ff75895d4417f8bb65b31b9d775c6?v=06c13b325c344e87af71d406cedcc52a&p=f2eac733a48f4e83af337a5cb2720561&pm=s)

AC: 
- When a listing closes, a banner displays on the applications tab indicating when a 
- After 45 days, applicant download in partners is disabled for Jurisdictional Admins and Partners.  
- After 45 days, applications tab in partners is disabled for Jurisdictional Admins and Partners

Notes: 
- Can we do this in a way where it's easy to change the time period after the listing closes? 
- Re-listing - Start the clock at the first time the listing closes
- BAHFA admins should still be able to download the application data

**Comment by sarahlazarich** [comment]
Want to avoid tabs that are viewable but not accessible 
- Maybe accompany this with notification? 

To follow up with Doorway: 
- Re-listing + re-open flow  (that could be a loophole, if they close then re-open or if a specific listing opens and reopens) 
- Block that flow, could just put it in draft to see it

**Comment by emilyjablonski** [comment]
QA Notes
As a JA/Partner, look at the applications tab on a closed listing and note the toast and the new export modal language.

After a listing has been closed for 45 days do the same to see the empty state.

Note that the [designs](https://www.figma.com/design/Kcsf148FqeUqMNeMo54BsW/Ad-Hoc-Feature-Enhancements?node-id=2418-16131&t=GrgB5GSjks17Y6t1-0) differed from the AC so we don't have a disabled tab
