### ISSUE TITLE
Allow the ability to turn on the common app for listings

### ISSUE THREAD

**Issue by ludtkemorgan** [metrotranscom/doorway#502]
The ability to turn on the common app in Doorway for a specific listing was commented out by the Google team. This was because applications were not in place. 

We will need to uncomment this code and make sure that it still works before launch on March 28th

QA Notes: https://staging.housingbayarea.mtc.ca.gov/
This can be tested by turning the common app on or off for an existing listing. Also, ensure that an external listing shows the helper text and an internal application does not

**Comment by sarahlazarich** [comment]
lgtm
