### ISSUE TITLE
Add data deletion notice to account settings

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#554]
As an housing seeker on Doorway, 
I want to know who to reach out to if I want all the data associated with my account deleted, 
So that I have a way to make that request if needed. 

[Design](https://www.figma.com/file/Kcsf148FqeUqMNeMo54BsW/Ad-Hoc-Feature-Enhancements?type=design&mode=design&t=Xwvti7c3og20OMjL-0)

AC: 
- When a user visits their account setting page, they should see a disclaimer letting them know who to reach out to in order to request that their data is deleted. 

Translations: 
- English: You can contact BAHFA to have your account information and associated data deleted at any time. To do so, please reach out to doorway@bayareametro.gov.
- Spanish: Puede comunicarse con BAHFA para eliminar la información de su cuenta y los datos asociados en cualquier momento. Para hacerlo, comuníquese con doorway@bayareametro.gov.
- Traditional Chinese: 您可以隨時聯絡 BAHFA 刪除您的帳戶資訊和相關資料。為此，請聯絡doorway@bayareametro.gov。
- Tagalog: Maaari kang makipag-ugnayan sa BAHFA upang matanggal ang impormasyon ng iyong account at nauugnay na data anumang oras. Upang gawin ito, mangyaring makipag-ugnayan sa doorway@bayareametro.gov.
- Vietnamese: Bạn có thể liên hệ với BAHFA để yêu cầu xóa thông tin tài khoản và dữ liệu liên quan của mình bất kỳ lúc nào. Để làm như vậy, vui lòng liên hệ với doorway@bayareametro.gov.

**Comment by sarahlazarich** [comment]
Can we standardize how deletion works?
- YL: There's technically an endpoint for deletion, but it's never been used, would need to test that 
- There should be better e2e tests, and testing with user data

**Comment by KrissDrawing** [comment]
QA Notes: after login go to `/account/edit` on bottom it should have disclaimer

**Comment by sarahlazarich** [comment]
lgtm
