### ISSUE TITLE
Bug: Region not populating on live/work question in non-English languages

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#555]
The region of a listing is not coming through in non-english languages. 

<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1TQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4a1f742d674b1aae536fb905681a9f336c5d4e4/image.png" alt="image.png" />

<img width="539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26a2fc3c28e6fb3896239c0f4804769f49e191ce/Screenshot%202024-03-26%20at%203.39.39%E2%80%AFPM.png" alt="Screenshot 2024-03-26 at 3.39.39 PM.png" />

**Comment by sarahlazarich** [comment]
This could be happening everywhere the region is dynamic - add %{county}

**Comment by KrissDrawing** [comment]
QA Notes: It should work dynamically now for above, and similar question for household member

**Comment by sarahlazarich** [comment]
lgtm!
