### ISSUE TITLE
Mandated Account Logic Cleanup

### ISSUE THREAD

**Issue by ColinBuyck** [metrotranscom/doorway#575]
A doorway listing that links to external listing is causing issues in both preview and active listings 

Previewing a listing resulting in the following confusing behavior: it directs me to sign into an applicant account, then opens a digital common app, then closes out saying "this listing is no longer accepting applications."

Generally, the mandated accounts is always redirecting to the sign in page when this should only happen when the listing is a Doorway listing (rather than HBA) and is using the common application

QA Doorways Staging:
This can be tested by taking an existing public listing on the partners side, adding a custom online application, and testing to see if the preview link and public link don't force you to sign in.

**Comment by sarahlazarich** [comment]
lgtm!
