### ISSUE TITLE
Remove Unused Ethnicity Demographics Code

### ISSUE THREAD

**Issue by mcgarrye** [metrotranscom/doorway#578]
1. Remove Ethnicity from api/src/dtos/applications/demographic.dto.ts
2. Remove references everywhere, which would include changes across public, partners, shared-helpers, and api

**Comment by sarahlazarich** [comment]
Used in Core & HBA - would this cause merge conflicts? 
Is removing better than ignoring them?  This currently isn't breaking anything? 

Decision: Closing --- YL would love if the BE was the same on all BEs 
Would rather leave things in place for consistency's sake
