### ISSUE TITLE
See Listing Misdirect

### ISSUE THREAD

**Issue by mcgarrye** [metrotranscom/doorway#599]
**Describe the bug**
`See Listing` button fails on first click after language has been changed. Works on second click.

**To Reproduce**
1. Sign into public account that has applications completed
2. Go to 'My Applications'
2. Click on any of the other languages offered
3. Click on the `See Listing` button

**Expected behavior**
`See Listing` button should not fail 

**Screenshots**

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0NxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fed425e628fa3045dfffcda791a6079417aea668/Screen%20Recording%202024-04-30%20at%201.38.48%E2%80%AFPM.mov)

**Comment by sarahlazarich** [comment]
Tested this, and I'm still seeing this behavior

**Comment by sarahlazarich** [comment]
talked over with @mcgarrye ,  looks like this is failing for the first few seconds after the language is changed but works after a few seconds. We're going to pass this one, since it's an improvement from the current behavior, and @mcgarrye is going to open up a follow-up for the latency issue.
