### ISSUE TITLE
Hover Text on form fields  

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#601]
**Describe the bug**

**To Reproduce**
Hover over form fields, see that there is some text that shows up.

**Expected behavior**
This should not show up when a user hovers over form fields.

**Screenshots**
<img width="1097" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ec58232f3b216242410cb72f8cd992bbdc31af4/Screenshot%202024-05-01%20at%205.35.27%E2%80%AFPM.png" alt="Screenshot 2024-05-01 at 5.35.27 PM.png"/>

**Additional context**
BAHFA's main concern here is that this would be read aloud by a screenreader. We verified that this is not the case, but we should see if we can remove this weird hover state in general.

**Comment by emilyjablonski** [comment]
QA Notes
We will have to pull in latest UIC in Doorway before we can QA. Ensure we aren't getting tooltips on hover anymore.

**Comment by emilyjablonski** [comment]
This is now QA-able as soon as it deploys to staging!

**Comment by sarahlazarich** [comment]
I believe this looks good! I don't see the tooltip hovering over the notification any more.
