### ISSUE TITLE
Partners Unable to Access Listings

### ISSUE THREAD

**Issue by iph-97** [metrotranscom/doorway#604]
Babs was onboarding two property managers today and they were unable to access their listings/log in properly while on the call. I followed the steps they took (detailed below) and was not able to replicate the issue. However, I'm flagging this as a high priority issue b/c of the current circumstances. Can we see 1) if there is an issue at play that we need to fix and 2) why this might be happening only to these users?

Dominic:
I created an account for Dominic
He received an email invitation from DPP
He created his account
He logged in
He didn't see the Rick Judd Commons listing that I assigned to him
I asked him to log out and log back in
He entered his email and password
He received a verification code
He entered the code
He got a massage saying 'please enter a valid code'
I watched him do these steps and his code was valid
He was using Chrome

Kathy:
Kathy has an existing account
I assigned Rick Judd Commons listing to her
She logged in
She couldn't see any listings that were assigned to her - she's got Aspen Court and Rick Judd Commons
I asked her to log out and log back in
She entered his email and password
She received a verification code
 She entered the code
She got a massage saying 'please enter a valid code'
I watched her do these steps and her code was valid
She was using Chrome

**Comment by sarahlazarich** [comment]
I don't think this issue is still relevant
