### ISSUE TITLE
Fetch assets from same file service they were stored in

### ISSUE THREAD

**Issue by ifranch** [metrotranscom/doorway#62]
With issues #20 and #49, we now have a way to change what third party file service we use in a configurable way. As of right now there are two possible options: Cloudinary and AWS S3. If we launch Doorway using AWS S3 and further down the line want to switch to Cloudinary or vice versa, we will need to migrate the data such as listing photos for existing listings to the new services.

An alternative to doing a data migration, or a solution in the meantime, is to fetch data from the original file service it was stored in. We currently only store the id for each asset (picture or document) but we do not store whether that is an AWS S3 id or a Cloudinary id. If we do expect to switch services in the future, in order to make the switch easier, we should also store which file service an asset is stored in. Then when reading the asset, instead of using the default file service at the time, we will use the implementation for the original file service to fetch it.

The changes necessary will be:
- Add a new field to store what file service an asset is stored in
- Set that field when putFile() is called
- Based on that field, use the correct file service implementation to get the download URL for the asset

**Comment by sarahlazarich** [comment]
closing, can reopen if there's a need
