### ISSUE TITLE
New CTAC Limits

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#624]
New tax credit (CTCAC) income limits have been published for 2024 Could the tables from Doorway jurisdictions(Contra Costa, Napa, Sonoma, Solano, Santa Clara, Marin) be added to DPP?

If there are issues with this format, we can ask Babs for a different one.

 [ctcac_income_4124.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXZmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab6816530586a9f4141d9d48f7c54ac324edec9f/ctcac_income_4124.pdf)

**Comment by sarahlazarich** [comment]
blocked by script runner

**Comment by sarahlazarich** [comment]
update format to csv

**Comment by sarahlazarich** [comment]
@mcgarrye https://docs.google.com/spreadsheets/d/1Y-xnK7RIwDCwhugZRJH8lqSf_458VE7ZNWckYsejq4I/edit#gid=277613817

**Comment by mcgarrye** [comment]
@sarahlazarich what should the naming be for each one? ex: "Napa - CTAC"? or "Napa - CA CTAC"? Or something else entirely?

**Comment by mcgarrye** [comment]
Per Izzie: This is the guidance our clients gave us: expect to see the following: Name of County or City; Regulatory agency name associated with the chart; applicable date. So "Napa CTAC 2024".
