### ISSUE TITLE
% of Income Rent Levels Decreasing by 1

### ISSUE THREAD

**Issue by iph-97** [metrotranscom/doorway#625]
Reported from Babs - "I'm drafting a couple of listings that charge rent based on income. When I indicate the percentage of income (so far it's always been 30), and select Save & Exit or select Make a Copy, and then I go back into the unit to edit the details, the percentage of income drops by one, and sometimes three (aka, 29, 27). I can edit the percentage to 30 and it will save. Not a big deal, but weird! Also could get annoying if I were making a bunch of copies of a unit that otherwise didn't need further editing." I'm going to tag this as low priority.

**Comment by sarahlazarich** [comment]
closing bc I consolidated it with her other related bug https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/658
