### ISSUE TITLE
Investigation - Terms of Service Agreements

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#630]
As a part of Application Launch, we also started to store records of a user accepting the Doorway Terms of service on partner account creation and exports with PII (applicant download in particular) when we released those after an application launch. Since we had [some bugs ](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/634) on these fields , can we verify that users are: 
 - Required to accept the terms of service when creating an applicant account & a record is stored
 - Required to accept the terms of service when creating an partner account & a record is stored 
 - Required to accept the terms of service when applying to a listing & a record is stored 
 - Required to accept the terms of service when downloading an applicant export & a record is stored

**Comment by sarahlazarich** [comment]
YL: Where did you see this?
EM: This was on the Application table, fix was merged in 
YL: Did it include E2E or unit tests? 
EM: Didn't add anything new - wasn't a BE issue, was being set correctly, but the FE was making an incorrect value comparison. Do we want a BE error to get thrown? FE was requiring that you accept, but was incorrectly sending the data to the BE?
YL: Can we save data without them accepting? 
EM: If you send directly to the API, you can save a paper app without them accepting terms of service?
Any findings can be follow up-tickets, this is just the investigation 

For now, just investigate this for Doorway, for later/Izzie: should we allow folks to enter paper apps if they don't accept the terms of service?

**Comment by mcgarrye** [comment]
Findings for: Required to accept the terms of service when creating an applicant account & a record is stored
FE sends correct data but BE does not save the field and thus is always set to false

**Comment by mcgarrye** [comment]
Findings for: Required to accept the terms of service when creating an partner account & a record is stored
FE sends correct data, BE saves the correct data, this flow works correctly

**Comment by mcgarrye** [comment]
Findings for: Required to accept the terms of service when applying to a listing & a record is stored
This has been fixed. FE sends correct data, BE saves the correct data, this flow works correctly

**Comment by mcgarrye** [comment]
Findings for: Required to accept the terms of service when downloading an applicant export & a record is stored
Required to download CSV, data is not sent or stored anywhere

**Comment by sarahlazarich** [comment]
@sarahlazarich to make follow-ups
