### ISSUE TITLE
Public Accounts - Account Info Saving 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#631]
**Bug:** 
On the Doorway Public site in the applicant accounts, if you edit account info, and press update, you see a banner that the field is updating successfully. However, when I go away from the page, then go back, the change isn't reflected. 

Expected Behavior: 
Users should be able to update their account information and have the changes reflected.

**Comment by sarahlazarich** [comment]
YL: known bug, this is updated, but not reflected unless you refresh, so we can just re-fetch?
EM: Also to add: if you make more than one change, only the last one saves right now.
YL: Yeah - idea would be to refetch user info after every update.

**Comment by emilyjablonski** [comment]
QA Notes
This is a core merge so it will need to be released in Doorway - until then we can test on [bloom.exygy.dev](https://bloom.exygy.dev/)

- Edit a field on the user account page, visit another page like the dashboard, go back in the browser and your change was not there
0 Edit a field on the user account page, edit another field, refresh, and only the second change persisted

**Comment by sarahlazarich** [comment]
lgtm!
