### ISSUE TITLE
Content Fixes 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#636]
Bug 1:
- On the Partner site account sign-up, Terms of Use links are not underlined in partner account sign-up legal disclosure modal. 

Expected Behavior 1: 
- This link should be underlined. 

Bug 2: 
- On the Public facing log-in page, there is a spelling error "Sign up quicky with no need to remember any passwords." <img width="1304" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFArQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ced403a69ada0c0de1ae039b987821bd7ee4387/image.png" alt="image.png" />

Expected Behavior 2: 
- Spelling error "Sign up quickly with no need to remember any passwords."

**Comment by KrissDrawing** [comment]
QA Notes: underlines were added also for export applications TOS accept modal

**Comment by sarahlazarich** [comment]
lgtm!!
