### ISSUE TITLE
Public Application - Household member address

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#640]
Bug:
Add a household member, add all of the optional addresses, save, go back to edit that household member, address fields are empty

Expected Behavior: 
Addresses should persist

**Comment by sarahlazarich** [comment]
EJ: This is an issue with how we're storing our in-progress application before it's submitted

**Comment by emilyjablonski** [comment]
QA Notes:
This was a core fix.

Add both a household member w both addresses, and a street2 on a primary applicant on a public application. Move forward and backward steps and ensure the data stays. Ensure the data is on the summary view before submission (only the main address for a household member will show). Ensure after an application is submitted that it shows up correctly in the partners site and that from the detail view you can view a member and from the edit view you can edit a member.

**Comment by sarahlazarich** [comment]
lgtm in Core
