### ISSUE TITLE
Add Contra Costa HA Program

### ISSUE THREAD

**Issue by iph-97** [metrotranscom/doorway#652]
Babs needs a program added to Doorway for a listing to be published June 4th. It would be awesome if we could get this in by then - specific request below. It will not need an application question. This is a medium priority issue :large_yellow_circle:.

Could we add a Housing Program for Contra Costa County titled "Section 8 Project-Based Voucher Program," with the following description: "The Contra Costa Housing Authority operates a Project Based Voucher (PBV) Program, which is a component of the Housing Choice Voucher Program. The PBV Program allows applicants to receive rental assistance while living in a specified privately-owned property. Through the PBV Program, the rental assistance is attached to a specified unit for up to forty years."

**Comment by sarahlazarich** [comment]
In case you need translations: 

English
Section 8 Project-Based Voucher Program

The Contra Costa Housing Authority operates a Project Based Voucher (PBV) Program, which is a component of the Housing Choice Voucher Program. The PBV Program allows applicants to receive rental assistance while living in a specified privately-owned property. Through the PBV Program, the rental assistance is attached to a specified unit for up to forty years

Spanish 
Programa de vales basado en proyectos de la Sección 8

La Autoridad de Vivienda de Contra Costa opera un Programa de Vales Basados ​​en Proyectos (PBV), que es un componente del Programa de Vales de Elección de Vivienda. El Programa PBV permite a los solicitantes recibir asistencia para el alquiler mientras viven en una propiedad privada específica. A través del Programa PBV, la asistencia para el alquiler se adjunta a una unidad específica por hasta cuarenta años.

Vietnamese
Chương trình Phiếu thưởng Dựa trên Dự án Phần 8

Cơ quan Quản lý Nhà ở Contra Costa vận hành Chương trình Phiếu thưởng Dựa trên Dự án (PBV), là một phần của Chương trình Phiếu Lựa chọn Nhà ở. Chương trình PBV cho phép người nộp đơn nhận được hỗ trợ tiền thuê nhà khi sống trong một tài sản thuộc sở hữu tư nhân được chỉ định. Thông qua Chương trình PBV, hỗ trợ tiền thuê nhà được gắn liền với một căn hộ cụ thể trong tối đa bốn mươi năm.

Chinese (Traditional) 
第 8 節 基於專案的優惠券計劃

康特拉科斯塔住房管理局實施基於專案的優惠券 (PBV) 計劃，該計劃是住房選擇優惠券計劃的一部分。 PBV 計劃允許申請人在居住在指定的私人房產時獲得租金援助。透過 PBV 計劃，租賃援助將附加到指定的單位長達四十年。

Tagalog 
Seksyon 8 Programa ng Voucher na Batay sa Proyekto

Ang Contra Costa Housing Authority ay nagpapatakbo ng isang Project Based Voucher (PBV) Program, na isang bahagi ng Housing Choice Voucher Program. Ang PBV Program ay nagpapahintulot sa mga aplikante na makatanggap ng tulong sa pag-upa habang naninirahan sa isang partikular na pribadong pag-aari na ari-arian. Sa pamamagitan ng Programa ng PBV, ang tulong sa pag-upa ay nakakabit sa isang tinukoy na yunit hanggang sa apatnapung taon.
