### ISSUE TITLE
Applicant Account Terms of Service

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#656]
Follow-up to [terms of service investigation](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/metrotranscom/doorway/630) 

Through this investigation, we found that when an applicant creates an account, the FE sends correct data but BE does not save the field and thus is always set to false.

AC: 
It should be required to accept the terms of service when creating an applicant account & a record is stored

This will be QA'd by @ColinBuyck

**Comment by sarahlazarich** [comment]
@ColinBuyck is this good to close?

**Comment by ColinBuyck** [comment]
Yep, just tested!
