### ISSUE TITLE
New Senior Veterans Community Type

### ISSUE THREAD

**Issue by iph-97** [metrotranscom/doorway#660]
We received a request from Doorway for a new Reserved Community Type called "Senior Veterans." This is for the properties Babs is working on, but she "doesn't expect it completed by June 4th." This is a medium priority request :large_yellow_circle:.
Description: Reserved for seniors 62+ years old who have served in the US military and who were honorably discharged.

**QA NOTES**
log into the partner site and add the new community type to a listing
go to the public site and make sure it comes through properly (and is translated correctly)

**Comment by sarahlazarich** [comment]
English: Senior Veterans
Spanish: Programa de vales basado en proyectos de la Sección 8
Chinese: 第 8 節 基於專案的優惠券計劃
Vietnamese: Chương trình Phiếu thưởng Dựa trên Dự án Phần 8
Tagalog: Seksyon 8 Programa ng Voucher na Batay sa Proyekto

**Comment by YazeedLoonat** [comment]
Hey @sarahlazarich this is ready for you to QA on doorway staging

**Comment by sarahlazarich** [comment]
thanks! lgtm.
