### ISSUE TITLE
Hide Do You Work in? Question from Common Application

### ISSUE THREAD

**Issue by ColinBuyck** [metrotranscom/doorway#677]
An urgent request from Doorway has come through that they would like the "Do you work in [jurisdiction] question to be removed from the common app since it doesn't reflect their use of the jurisdictional field.

Since it is used throughout the application, this ticket only removes it from the common app but a full removal should be done as part of #678 

QA:https://staging.housingbayarea.mtc.ca.gov/
This can be tested by filling out the common app and noticing that the question doesn't appear on the address page nor the household member section.

**Comment by sarahlazarich** [comment]
lgtm!!!!!!!!!!
