### ISSUE TITLE
feat: add file upload endpoint to asset service

### ISSUE THREAD

**Issue by chriscasto** [metrotranscom/doorway#74]
File uploads currently rely on a multi-stage handshake with the backend asset service, with the actual upload being handled by client-side code.  This is less secure than handling file uploads as an atomic operation on the backend and requires touching multiple packages/services to make changes to upload behavior.  This feature would consolidate asset upload logic to a single API call on the backend and simplify the logic on the client side.

**Comment by sarahlazarich** [comment]
done, closing
