### ISSUE TITLE
Monthly Rent Filter on public site failing

### ISSUE THREAD

**Issue by YazeedLoonat** [metrotranscom/doorway#744]
there is currently an issue with filtering the listings on doorway's public site via the monthly rent filters.
It seems like its a data issue, but a hotfix is possible
technical explanation:
When trying to use the monthly rent filters a query that looks like
```
select DISTINCT 
    combined.id AS id
From combined_listings combined, jsonb_array_elements(combined.units) combined_units
WHERE (combined_units->>'monthlyRent')::INTEGER >= '101';
```
is constructed. In the database when we do the (combined_units->>'monthlyRent')::INTEGER cast some of those values are actually stored floating point numbers and cause the cast to fail which causes the filtering to fail
after talking with Eric we think the easiest fix may be to change the way this comparison works so that it looks like
```
select DISTINCT 
    combined.id AS id
From combined_listings combined, jsonb_array_elements(combined.units) combined_units
WHERE (combined_units->>'monthlyRent')::FLOAT >= '101'; 
```
When the query goes to run (where the value is cast as a floating point number always)

QA:
Test the Max Monthly Rent filter on the landing page and the Min/Max Rent filters on the listings page.

**Comment by sarahlazarich** [comment]
Add some seeded data with decimals for ease of testing

**Comment by sarahlazarich** [comment]
this lgtm
