### ISSUE TITLE
Lottery Opt In - Manual Update follow-up

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#747]
Follow up to [this](https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/gh/bloom-housing/bloom/4171) that we pulled in for the pilot. 

As a DPP user on a listing that is opted out of the system lottery, 
I want to be able to upload a PDF of my lottery results manually
So that I can share the results with the portal users. 

As a DPP user on a listing that is NOT opted out of the system lottery
I should not be able to manually upload results 
So that I do not upload results that confuse users. 

Note:
- We had planned to shift this ticket around this ticket for the pilot. 

AC:
- The manual upload is available on listings that are opted out of the system lottery
- Manually uploaded files show on the listing on the public site, and can be downloaded by the user 
- The manual upload is not available on listings that are using the system lottery

**Comment by emilyjablonski** [comment]
QA Notes
When the lottery toggle is on, on a closed listing with a lottery type, if a user is opted into the system lottery ensure they cannot see the post results button. Opt out of the lottery and save, and when re-entering the edit state the post results button should be available. You will have to save in between states.
