### ISSUE TITLE
refactor: asset url resolution

### ISSUE THREAD

**Issue by chriscasto** [metrotranscom/doorway#78]
Both the partner site and the public site rely on some helper functions (defined in `shared-helpers`) to determine the appropriate URL for an `Asset` object.  These functions collectively provide some level of abstraction, but are used inconsistently across the two sites, resulting in unnecessary duplication and widespread impact for otherwise minor changes.  They also encapsulate logic that could easily be consolidated on the backend with some minor changes.

The helpers that provide this functionality should be refactored into appropriately scoped and named functions that can be used by the sites to get the URLs needed with minimal knowledge about implementation.  They should be designed so that, should the logic be centralized on the backend, no additional changes would need to be made to frontend code for resolving file URLs.  Both sites should be updated to make use of the updated functions.

**Comment by sarahlazarich** [comment]
done, closing
