### ISSUE TITLE
SMC's Historical Application Data Pull

### ISSUE THREAD

**Issue by mcgarrye** [metrotranscom/doorway#788]
Doorway is running a test of some k-anonymization processes, and would like to test on SMC's historical application data. Can we please get a pull of all of their historical application data with the PII columns removed? PII columns are identified in this spreadsheet on the tab "Application-related fields" in the PII column (if it says 'yes', don't include it)

https://docs.google.com/spreadsheets/d/1npqkMoNQGQT68aP5ZxRj421nDGy5nf2e1xF5LeLsQgE/edit?usp=sharing

Included all applications on closed and open listings.
Barry stated that he wants age at time of application instead of age. This can be achieved using an excel 'diff' formula function that calculates the difference between DOB and date of application submitted, with the text format set to years. Lmk if you need his assistance with this piece"

**Comment by sarahlazarich** [comment]
Okay - on hold. Izzie is going to take a crack at doing this manually.
