### ISSUE TITLE
fix: add runtime config object/functions to public and partner sites

### ISSUE THREAD

**Issue by chriscasto** [metrotranscom/doorway#81]
# Background

Next.js burns all environment variables into the config at build time, then overwrites `process.env` at runtime with those values.  This is a huge violation of software development best practices and produces unexpected and inconsistent results.

This is also not cloud- or docker-friendly.  Docker is designed to "build once, run anywhere"; it's part of what makes it such a powerful technology.  By forcing build-time vs run-time configuration, each deployment of the public and partner sites will instead need to be built separately.  Since each build can take 10-20+ minutes, this significantly increases the time from merge to delivery.  It also slows down development velocity, as simply changing an env var when testing locally requires a full rebuild.

There is no way to disable this behavior in Next.js.  The `serverRuntimeConfig` and `publicRuntimeConfig` objects are considered legacy and are hit-or-miss when it comes to working as expected.  The good news is that run time env vars are still available on the server side, and so can be used in place of Next config values.

# Proposal

This issue proposes a runtime configuration package/object in that provides functions/methods for resolving configuration values at run time.  This will provide a level of abstraction around implementation and would provide a single point where run time values can be defined and modified as needed, while also providing a mechanism for building values dynamically when necessary (ie default, composite, and/or derived values).  While there would be some level of overlap between the config for the public and partner sites, each would have their own instance with independent functions.

Not all config values will need to implemented in the run time config.  Some are unlikely to ever change (supported languages, etc) or may actually be used by the build process (TBD).  This proposal recommends starting with values that are known or likely to change between environments (endpoint URLs, etc) and adding to this incrementally as needed.

# Risks

Some config values may be used by the client side rather than the server side, and due to the way Next.js configs work there's no way to tell which is which.  This will take some additional investigation to determine which vars are used where, and it may be necessary to implement some additional code and/or workarounds to pass certain config values from server to client side, especially on the partner site.  It is hoped that all needed values in both sites will be able to be incorporated with little effort, but if it is determined that the fix cannot be implemented in a reasonable timeframe, the fallback will be to implement a full rebuild cycle for whichever services cannot be fully corrected.

# Resources
https://12factor.net/config
https://en.wikipedia.org/wiki/Principle_of_least_astonishment
https://github.com/vercel/next.js/discussions/15651
https://github.com/vercel/next.js/discussions/39080
https://github.com/vercel/next.js/discussions/39899
https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration

**Comment by sarahlazarich** [comment]
done, closing
