### ISSUE TITLE
Spike - Map Improvements

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#851]
Overview of future changes is [here](https://docs.google.com/document/d/1jwy4uX-fdk5Rs4Stc4br5OyuhUr7QQMHQ4ZoU4Nh9_w/edit#heading=h.z2we68wtdnff)

We should: 
- Create a TDD (lightweight if needed!) 
- Review doc with team

**Comment by sarahlazarich** [comment]
Potential gotcha: 
- Mobile view scrolls to the listing - why do we have two different experiences? The space & screen real estate is hard. 
- How hard would it be to toggle between listing + map view instead of having to show both? Depending on the design, not so hard.
- What is common practice on mobile maps? 

We probably need to start w mobile designs

**Comment by emilyjablonski** [comment]
TDD: https://docs.google.com/document/d/1JH5dQ6IBXOJo1nbO1TPxEguhyyCXBkCBsD07gO-Ns5E/edit
