### ISSUE TITLE
School Employee Community Type 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#853]
Create a new community type in Doorway for "School Employee"

AC: 
- DPP user can create select a "School Employee" community type on a listing 
- If it's selected, on the public site, a "School Employee" community type shows as a tag on the listing picture 
- If it's selected, on the public site, a "School Employee" community type tag translates correctly
- If it's selected, on the public site, a "School Employee" community type shows as detail page and translates correctly

**Comment by sarahlazarich** [comment]
check what this looks like w other languages 
YL made a script, minor updates for translations

**Comment by ludtkemorgan** [comment]
@sarahlazarich I ran this through google translations. Are any of these too long?
- Spanish: "Empleado de la escuela"
- Vietnamese: "Nhân viên trường học"
- Chinese: "学校员工"
- Filipino: "empleyado ng paaralan"

**Comment by ludtkemorgan** [comment]
@sarahlazarich this has been merged to core and the script run in the dev environment. Translations still need to be confirmed so can you verify those in your QAing?

QA notes:
- https://bloom.exygy.dev/listings has the new reserved type on `Valley Heights Senior Community` property
- You should also be able to add it to new listings on https://partners.bloom.exygy.dev/

**Comment by ludtkemorgan** [comment]
This has been run in production and School Employee community type is now there
