### ISSUE TITLE
DHP landing page updates 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#887]
BAHFA would like to make some tweaks to the DHP home page. 
 
- [Design](https://www.figma.com/design/Kcsf148FqeUqMNeMo54BsW/Ad-Hoc-Feature-Enhancements?node-id=3717-2118&node-type=canvas&t=f2ZAGsvAvbWJ0YvR-0)
- [Copy Document](https://docs.google.com/document/d/1FgzXMPLY-egM-TRIHbxxgXbkWlaMev7EspnU7PeZMlU/edit?usp=sharing) 

Notes: 
- The Data Viz banner should not be visible until the feature flag is turned on and the link to the correct MTC page is provided. 
- Translations can be in google translate

AC: 
- "Welcome" Section should be removed from the page
- Move "sign up" section up to under the filter & update colors
- Switch questions / help columns in get started section & update copy
- Hyperlink the BAHFA logo in footer to https://mtc.ca.gov/about-mtc/authorities/bay-area-housing-finance-authority-bahfa
- Update the copyright in footer to "Copyright 2024"

**Comment by emilyjablonski** [comment]
QA Notes
Compare the homepage and footer (which was fully rewritten) to the [Figma](https://www.figma.com/design/Kcsf148FqeUqMNeMo54BsW/Ad-Hoc-Feature-Enhancements?node-id=3717-2118&node-type=canvas&t=IXrIQJDfeZCKphfJ-0)

**Comment by sarahlazarich** [comment]
lgtm
