### ISSUE TITLE
Create new endpoint for listings 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#889]
Create two new endpoints to return simplified listing data.

- One endpoint to pull for map data for all listings 
- Take the Listing get by ID endpoint and modify it to take in an optional "view" param. Where the views are "base" for the regular view and "card" for the card view. Where the "card" view returns just the data for the card and the "base" view is what the endpoint normally returns

Use the new endpoints to return latitude and longitude for each listing, and populate the map using that. 

Doc: https://docs.google.com/document/d/1JH5dQ6IBXOJo1nbO1TPxEguhyyCXBkCBsD07gO-Ns5E/edit#heading=h.bknox3ib8wpb

**Comment by mcgarrye** [comment]
QA Notes: Product cannot QA
