### ISSUE TITLE
Documentation for Glenn 

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#942]
We need to start doing some knowledge transfer and allow glenn to take on some of our support burden after our Doorway contract. Let's start by writing up some documentation instructing him how to check questions such as: 
- Who submitted this listing for approval?
- Does this user have an account?
- What is the recent system log/user behavior?
- Check emails / SES 

It might make sense to write up a few common queries and instructions for him on how to run.

**Comment by ludtkemorgan** [comment]
The work for this has begun in this document https://docs.google.com/document/d/1ELW-8IJVqCQ71xZ1Bz2GQKooJ35_0CNEvlC9NWZIqgA/edit?tab=t.0
