### ISSUE TITLE
Remove SMC referral sections in Doorway

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#988]
Bug: 
The referral sections on SMC listings are showing up in Doorway. 

<img width="1175" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFVQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8036109c06d957d098dc0dfb86fa1486fb9d540c/image.png" alt="image.png" />

Fix: 
We will go through all of the listings that were ported over from SMC and remove any of the referral sections below. We should also add this to our runbook for the next jurisdiction we transition into Doorway as well.

**Comment by sarahlazarich** [comment]
Postgres script was run on Friday that removes this 
@YazeedLoonat to post the script he used to fix one listing 
That script is extendable, and we should be able to use that to do this long term

**Comment by YazeedLoonat** [comment]
```
-- tells you how many you are going to delete
SELECT
    SUM(1)
FROM application_methods
WHERE listing_id IN ('d6d08820-a870-4549-9040-8ca05b969c21')
    AND type = 'Referral';

-- deletes them
DELETE FROM application_methods
WHERE listing_id IN ('d6d08820-a870-4549-9040-8ca05b969c21')
    AND type = 'Referral';
```

**Comment by mcgarrye** [comment]
The only listing with a referral section was a draft listing Yazeed made during his investigation and resolution of the previous issue. This test listing has been deleted and no other listing have referral sections on Doorway
